export const rooms = [
  {
    name: "Charming Studio < 10 Miles to Wells' Beaches!",
    pricePerNight: 168,
    description:
      'A friendly atmosphere and natural delights await your visit to the town of Wells! Stay at this well-equipped 1-bath studio and enjoy easy access to several beaches, including Wells Beach and Drakes Island Beach, as well as Rachel Carson National Wildlife Refuge - the best spot for wildlife viewing just 8 miles away. Not to mention, with the downtown area just 10 minutes from vacation rental.',
    address: '4667 Bicetown Street, New York, NY, 10004',
    guestCapacity: 1,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: false,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/ny4n2w1ubdnfktua8stg',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693135931/bookit/demo/ny4n2w1ubdnfktua8stg.jpg',
      },
      {
        public_id: 'bookit/demo/ao7enhxobr0z1qyxgyki',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693135931/bookit/demo/ao7enhxobr0z1qyxgyki.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Picturesque 2-Story Farmhouse w/Private Hot Tub',
    pricePerNight: 242,
    description:
      'Find plenty of space for a family or a large group at this picturesque Wells home, the perfect spot for a relaxing getaway in charming, quintessential Maine style! Spend your days on the beautiful nearby beaches, and come home to a large backyard and orchard where your kids can play, as well as a patio with a gas grill for barbecues on summer afternoons.',
    address: '200 Olympic Dr, Stafford, VS, 22554',
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/gbabqnb7nzvc7gmmpcvg',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136060/bookit/demo/gbabqnb7nzvc7gmmpcvg.jpg',
      },
      {
        public_id: 'bookit/demo/tvheutup1idr5wi0p5bq',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1694680598/bookit/demo/tvheutup1idr5wi0p5bq.jpg',
      },
    ],
    category: 'Twins',
    reviews: [],
  },
  {
    name: 'Downtown Portsmouth Private Getaway! Hot Tub',
    pricePerNight: 85,
    description:
      'Absolutely the best location in Portsmouth! Beautifully furnished, this spacious and private home is perfectly suited for taking in all of the must-see sights and historic landmarks that make this vibrant city so unique. Situated near the banks of the Piscataqua River just minutes away from Strawbery Banke Museum, Prescott Park, USS Albacore Museum, Market Square and more!',
    address: '3747 Parkway Street, Apple Valley, CA, 92307',
    guestCapacity: 3,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/nhhthdrrvaundinfnyxd',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136187/bookit/demo/nhhthdrrvaundinfnyxd.jpg',
      },
      {
        public_id: 'bookit/demo/qsmprvvkshpwynqinz8i',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136187/bookit/demo/qsmprvvkshpwynqinz8i.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Spacious Suite in a quiet Boston neighborhood.',
    pricePerNight: 95,
    description:
      'Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.',
    address: '224 Cherry St, Buffalo, NY, 14202',
    guestCapacity: 6,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/ahxbixikavvrlokgf8jp',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/ahxbixikavvrlokgf8jp.jpg',
      },
      {
        public_id: 'bookit/demo/m7hgvpqj6kbqjsma0gfy',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/m7hgvpqj6kbqjsma0gfy.jpg',
      },
      {
        public_id: 'bookit/demo/inpn3k94tvsmdaun0dsj',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136394/bookit/demo/inpn3k94tvsmdaun0dsj.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Shangri-La Hotel, Washington',
    pricePerNight: 105,
    description:
      'Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.',
    address: '4724  Mudlick Road, Yakima, WA, 98902',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/ir1705u1vtfgzvqqdfh2',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136765/bookit/demo/ir1705u1vtfgzvqqdfh2.jpg',
      },
      {
        public_id: 'bookit/demo/o3ieyr8gltwhwccgqzia',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136765/bookit/demo/o3ieyr8gltwhwccgqzia.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Hotel Chimayo de Santa Fe Rooms',
    pricePerNight: 36,
    description:
      'Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.',
    address: '1029  Godfrey Street, Portland, OR, 97205',
    guestCapacity: 2,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/hmvqt42lzdjc197ynrtk',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136789/bookit/demo/hmvqt42lzdjc197ynrtk.jpg',
      },
    ],
    category: 'Twins',
    reviews: [],
  },
  {
    name: 'Hotel Garni Ischgl 4 star room comfort',
    pricePerNight: 82,
    description:
      'Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.',
    address: '2645  Parrish Avenue, SAINT LOUIS, MO, 63116',
    guestCapacity: 5,
    numOfBeds: 3,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: false,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/aenyd4econmkcvyiyjkc',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136804/bookit/demo/aenyd4econmkcvyiyjkc.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'The Spa at Base Camp at Kerry Hotel',
    pricePerNight: 76,
    description:
      'Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.',
    address: '3118  Red Hawk Road, Garfield, MN, 56332',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'The Spa at Base Camp at Kerry Hotel',
    pricePerNight: 76,
    description:
      'Our largest room with a queen bed and foldable sofa. Comfortably fits 2-3 adults, four adults maximum. Decorated with Irish-themed colors and arts. It has a private bathroom with a shower, equipped with smart TV, mini-fridge, desk, chairs. Enjoy City views at the sitting area by the window. Located on the 3rd floor with no elevator.',
    address: '3118 Red Hawk Road, Garfield, MN, 56332',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Sunset Boulevard Suite',
    pricePerNight: 120,
    description:
      'A luxurious suite with a king bed and a spectacular view of the sunset. The suite is furnished with modern decor, featuring a private bathroom with a Jacuzzi, a smart TV, mini-bar, desk, and lounge chairs. Perfect for a romantic getaway. Located on the 5th floor with elevator access.',
    address: '9876 Sunset Boulevard, Beverly Hills, CA, 90210',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Mountain View Cabin',
    pricePerNight: 90,
    description:
      'A cozy cabin with stunning mountain views, featuring a queen bed and a small living area. The cabin is decorated with rustic charm, including a private bathroom with a shower, a smart TV, mini-fridge, and a fireplace. Ideal for nature lovers. Located on the ground floor.',
    address: '1234 Mountain Road, Boulder, CO, 80302',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: false,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Oceanfront Paradise',
    pricePerNight: 200,
    description:
      'A beautiful oceanfront room with a balcony and breathtaking views of the sea. It includes a king bed, private bathroom with a luxurious bath, a smart TV, mini-bar, and a seating area. Perfect for a relaxing beach vacation. Located on the 7th floor with elevator access.',
    address: '4567 Ocean Drive, Miami Beach, FL, 33139',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Cozy Downtown Studio',
    pricePerNight: 65,
    description:
      'A comfortable studio apartment in the heart of downtown. Features a queen bed, private bathroom with a shower, smart TV, mini-fridge, and a small kitchenette. Ideal for business travelers. Located on the 2nd floor with elevator access.',
    address: '345 Main Street, New York, NY, 10001',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Historic City Bungalow',
    pricePerNight: 110,
    description:
      'A charming bungalow in the historic district. Features a king bed, private bathroom with a clawfoot tub, smart TV, mini-fridge, and antique furnishings. Perfect for a cultural trip. Located on the ground floor.',
    address: '789 Heritage Street, Charleston, SC, 29401',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Twins',
    reviews: [],
  },
  {
    name: 'Luxury Penthouse',
    pricePerNight: 300,
    description:
      'An exquisite penthouse with panoramic city views. Features a king bed, private bathroom with a Jacuzzi, smart TV, full kitchen, and a spacious living area. Ideal for luxury travelers. Located on the top floor with elevator access.',
    address: '1010 High Street, San Francisco, CA, 94109',
    guestCapacity: 4,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Countryside Cottage',
    pricePerNight: 80,
    description:
      'A quaint cottage in the countryside. Features a queen bed, private bathroom with a shower, smart TV, mini-fridge, and a cozy fireplace. Perfect for a peaceful retreat. Located on the ground floor.',
    address: '5678 Country Lane, Nashville, TN, 37209',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: false,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'City Center Loft',
    pricePerNight: 150,
    description:
      'A modern loft in the city center. Features a king bed, private bathroom with a rain shower, smart TV, mini-bar, and a contemporary kitchen. Perfect for urban explorers. Located on the 10th floor with elevator access.',
    address: '4321 Downtown Avenue, Seattle, WA, 98101',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Beachfront Villa',
    pricePerNight: 250,
    description:
      'A stunning villa with direct beach access. Features a king bed, private bathroom with a soaking tub, smart TV, full kitchen, and a large patio. Perfect for a beach vacation. Located on the ground floor.',
    address: '6789 Beach Road, Malibu, CA, 90265',
    guestCapacity: 4,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Desert Oasis',
    pricePerNight: 180,
    description:
      'A serene retreat in the desert. Features a king bed, private bathroom with a walk-in shower, smart TV, mini-fridge, and a large deck. Ideal for a peaceful getaway. Located on the ground floor.',
    address: '1234 Desert Road, Phoenix, AZ, 85001',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Mountain Chalet',
    pricePerNight: 220,
    description:
      'A luxurious chalet in the mountains. Features a king bed, private bathroom with a sauna, smart TV, full kitchen, and a spacious living area with a fireplace. Perfect for a winter vacation. Located on the ground floor.',
    address: '5678 Chalet Lane, Aspen, CO, 81611',
    guestCapacity: 4,
    numOfBeds: 2,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Twins',
    reviews: [],
  },
  {
    name: 'Historic Mansion',
    pricePerNight: 400,
    description:
      'A grand mansion with period furnishings. Features a king bed, private bathroom with a clawfoot tub, smart TV, mini-bar, and a spacious living area. Perfect for a luxurious getaway. Located on the ground floor.',
    address: '7890 Mansion Lane, Newport, RI, 02840',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Twins',
    reviews: [],
  },
  {
    name: 'Ski Resort Lodge',
    pricePerNight: 300,
    description:
      'A cozy lodge in the mountains. Features a king bed, private bathroom with a hot tub, smart TV, mini-bar, and a fireplace. Perfect for a winter getaway. Located on the ground floor.',
    address: '1010 Lodge Lane, Vail, CO, 81657',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Beachfront Resort',
    pricePerNight: 350,
    description:
      'A luxurious resort with direct beach access. Features a king bed, private bathroom with a Jacuzzi, smart TV, mini-bar, and a large balcony. Perfect for a beach vacation. Located on the ground floor.',
    address: '4321 Resort Lane, Maui, HI, 96761',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'King',
    reviews: [],
  },
  {
    name: 'Safari Tent',
    pricePerNight: 150,
    description:
      'A luxurious tent in the wilderness. Features a king bed, private bathroom with a rain shower, smart TV, mini-bar, and a large deck. Perfect for a glamping adventure. Located on the ground floor.',
    address: '5678 Safari Lane, Serengeti, Tanzania',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
  {
    name: 'Mountain Cabin',
    pricePerNight: 120,
    description:
      'A cozy cabin in the mountains. Features a queen bed, private bathroom with a shower, smart TV, mini-fridge, and a fireplace. Perfect for a nature retreat. Located on the ground floor.',
    address: '1234 Cabin Lane, Lake Tahoe, CA, 96150',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: false,
    isAirConditioned: false,
    isPetsAllowed: true,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Twins',
    reviews: [],
  },
  {
    name: 'Beachfront Bungalow',
    pricePerNight: 180,
    description:
      'A charming bungalow with direct beach access. Features a queen bed, private bathroom with a shower, smart TV, mini-fridge, and a small patio. Perfect for a beach getaway. Located on the ground floor.',
    address: '6789 Bungalow Lane, Bali, Indonesia',
    guestCapacity: 2,
    numOfBeds: 1,
    isInternet: true,
    isBreakfast: true,
    isAirConditioned: true,
    isPetsAllowed: false,
    isRoomCleaning: true,
    ratings: 0,
    numOfReviews: 0,
    images: [
      {
        public_id: 'bookit/demo/bwrnbs3sqzd6bbuyau47',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136823/bookit/demo/bwrnbs3sqzd6bbuyau47.jpg',
      },
      {
        public_id: 'bookit/demo/hhjpp67jiqyacv8gvmso',
        url: 'http://res.cloudinary.com/udemy-courses/image/upload/v1693136822/bookit/demo/hhjpp67jiqyacv8gvmso.jpg',
      },
    ],
    category: 'Single',
    reviews: [],
  },
];
